version: "3.8"
services:
  nginx:
    container_name: nginx
    image: nginx
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    ports:
      - "443:443"
    restart: always
    #depends_on:
      #- wordpress
    #volumes:
      #- wordpress:/var/www/html/wordpress
    #networks:
      #- ft_inception
  #mariadb:
    # container_name: mariadb
    # image: mariadb
    # ports:
    #   - "3306:3306"
  