version: "3.8"
services:
    nginx:
        container_name: nginx
        image: nginx
        build:
            context: ./requirements/nginx
            dockerfile: Dockerfile
        ports:
            - "443:443"
        restart: on-failure
        volumes:
            - wordpress_data:/var/www/html/wordpress
        networks:
            - ft_inception
    mariadb:
        container_name: mariadb
        image: mariadb
        build:
            context: requirements/mariadb/
            args:
                - DB_NAME=$DB_NAME
                - DB_USER=$DB_USER
                - DB_PASSWORD=$DB_PASSWORD
                - DB_PASSWORD_ROOT=$DB_PASSWORD_ROOT
        volumes:
                - mariadb_data:/var/lib/mysql
        env_file:
            - .env
        restart: on-failure
        networks:
            - ft_inception
    wordpress:
        container_name: wordpress
        image: wordpress
        environment:
            WP_TITLE: $(WP_TITLE)
            WP_USER: $(WP_USER)
            WP_USER_PW: $(WP_USER_PW)
            WP_USER_MAIL: $(WP_USER_MAIL)
            WP_ADMIN: $(WP_ADMIN)
            WP_ADMIN_PW: $(WP_ADMIN_PW)
            WP_ADMIN_MAIL: $(WP_ADMIN_MAIL)
            DB_HOST: $(DB_HOST)
            DN: $(DN)
        restart: on-failure
        build:
            context: ./requirements/wordpress
            dockerfile: Dockerfile
        volumes:
            - wordpress_data:/var/www/html
        networks:
            - ft_inception
volumes :
    mariadb_data:
        driver: local
        driver_opts:
            type: "none"
            o: "bind"
            device: /home/nmilan/data/
    wordpress_data:
        driver: local
        driver_opts:
            type: "none"
            o: "bind"
            device: /home/nmilan/data/

networks:
    ft_inception:
        name: ft_inception
        driver: bridge
  