version: "3.8"
services:
    mariadb:
        container_name: mariadb
        image: mariadb
        build:
            context: requirements/mariadb/
            args:
                - DB_NAME=$DB_NAME
                - DB_USER=$DB_USER
                - DB_PW=$DB_PW
                - DB_ROOT_PW=$DB_ROOT_PW
        volumes:
                - mariadb_data:/var/lib/mysql:rw
        env_file:
            - .env
        restart: on-failure
        networks:
            - ft_inception
    wordpress:
        container_name: wordpress
        image: wordpress
        env_file:
            - .env
        restart: on-failure
        build:
            context: ./requirements/wordpress
            dockerfile: Dockerfile
        depends_on:
            - mariadb 
        volumes:
            - wordpress_data:/var/www/wordpress:rw
        networks:
            - ft_inception
    nginx:
        container_name: nginx
        image: nginx
        build:
            context: ./requirements/nginx
            dockerfile: Dockerfile
        ports:
            - "443:443"
        restart: on-failure
        volumes:
            - wordpress_data:/var/www/wordpress:rw
        networks:
            - ft_inception
        depends_on:
            - wordpress
volumes :
    mariadb_data:
        driver: local
        driver_opts:
            type: "none"
            o: "bind"
            device: /home/nmilan/data/mariadb
    wordpress_data:
        driver: local
        driver_opts:
            type: "none"
            o: "bind"
            device: /home/nmilan/data/wordpress

networks:
    ft_inception:
        name: ft_inception
        driver: bridge
  